import { CORP } from './types';

const corporations: CORP[] = [
  {
    id: 1,
    name: '삼성전자',
    eng: 'Samsung',
    image: 'images/samsung.png',
  },
  {
    id: 2,
    name: 'SK하이닉스',
    eng: 'Skhynix',
    image: 'images/hynix.png',
  },
  {
    id: 3,
    name: '삼성바이오로직스',
    eng: 'Samsungbio',
    image: 'images/samba.png',
  },
  {
    id: 4,
    name: 'LG화학',
    eng: 'Lgchemistry',
    image: 'images/lgChem.png',
  },
  {
    id: 5,
    name: '네이버',
    eng: 'Naver',
    image: 'images/naver.png',
  },
  {
    id: 6,
    name: '현대차',
    eng: 'Hyundai',
    image: 'images/hyundai.png',
  },
  {
    id: 7,
    name: '카카오',
    eng: 'Kakao',
    image: 'images/kakao.png',
  },
  {
    id: 8,
    name: '삼성SDI',
    eng: 'SamsungSDI',
    image: 'images/sdi.png',
  },
  {
    id: 9,
    name: '셀트리온',
    eng: 'cell',
    image: 'images/celltrion.png',
  },
  {
    id: 10,
    name: '기아',
    eng: 'kia',
    image: 'images/kia.png',
  },
  {
    id: 11,
    name: '포스코',
    eng: 'Posco',
    image: 'images/posco.png',
  },
  {
    id: 12,
    name: '현대모비스',
    eng: 'Mobis',
    image: 'images/mobis.png',
  },
  {
    id: 13,
    name: '삼성물산',
    eng: 'SamsungMul',
    image: 'images/moolsan.png',
  },
  {
    id: 14,
    name: 'SK 이노베이션',
    eng: 'SkIno',
    image: 'images/sk_inno.png',
  },
  {
    id: 15,
    name: 'LG전자',
    eng: 'LgElectro',
    image: 'images/lgElectro.png',
  },
  {
    id: 16,
    name: 'LG생활건강',
    eng: 'LgLife',
    image: 'images/lgLife.png',
  },
  {
    id: 17,
    name: 'KB금융',
    eng: 'Kb',
    image: 'images/kb.png',
  },
  {
    id: 18,
    name: 'SK텔레콤',
    eng: 'Skt',
    image: 'images/skt.png',
  },
  {
    id: 19,
    name: '신한지주',
    eng: 'Shinhan',
    image: 'images/sinhan.png',
  },
  {
    id: 20,
    name: 'SK',
    eng: 'Sk',
    image: 'images/sk.png',
  },
  {
    id: 21,
    name: '엔씨소프트',
    eng: 'Nc',
    image: 'images/ncsoft.png',
  },
  {
    id: 22,
    name: '한국전력',
    eng: 'KoreaElectro',
    image: 'images/koreaElectro.png',
  },
  {
    id: 23,
    name: '삼성생명',
    eng: 'SamsungLife',
    image: 'images/samsungLife.png',
  },
  {
    id: 24,
    name: '아모레퍼시픽',
    eng: 'Amore',
    image: 'images/amore.png',
  },
  {
    id: 25,
    name: 'LG',
    eng: 'LG',
    image: 'images/lg.png',
  },
  {
    id: 26,
    name: 'HMM',
    eng: 'Hmm',
    image: 'images/hmm.png',
  },
  {
    id: 27,
    name: '삼성SDS',
    eng: 'SamsungSDS',
    image: 'images/sds.png',
  },
  {
    id: 28,
    name: '하나금융지주',
    eng: 'Hana',
    image: 'images/hana.png',
  },
  {
    id: 29,
    name: '삼성전기',
    eng: 'SamsungElectro',
    image: 'images/samsungElectro.png',
  },
  {
    id: 30,
    name: '넷마블',
    eng: 'Netmarble',
    image: 'images/netmarble.png',
  },
];

export default corporations;
